.github/workflows/pr.yaml, Dockerfile, package.json, src/pages/edp-stage-details/providers/DynamicData/provider.tsx
Patch updates: 
* Add menu switcher
* Show sub-menu on mouse hover
=> chore: Update headlamp image tag

Dockerfile, src/widgets/CreateCodebaseBranch/components/fields/BranchName/index.tsx, src/widgets/CreateCodebaseBranch/components/fields/ReleaseBranchName/index.tsx, src/widgets/ManageDefectDojo/components/QuickLink/fields/ExternalURL/index.tsx, src/widgets/ManageDefectDojo/components/Secret/fields/Token/index.tsx, src/widgets/ManageDependencyTrack/components/QuickLink/fields/ExternalURL/index.tsx, src/widgets/ManageDependencyTrack/components/Secret/fields/Token/index.tsx, src/widgets/ManageSonar/components/QuickLink/fields/ExternalURL/index.tsx, src/widgets/ManageSonar/components/Secret/fields/Token/index.tsx
- Fix branch/release branch validation messages
- Fix integrations Token/QuickLink validation messages and titles
- Update headlamp image
=> fix: Fix branch validation, fix integrations labels

src/k8s/EDPGitServer/types.ts, src/pages/edp-configuration/pages/edp-gitserver-list/providers/DynamicData/context.ts, src/pages/edp-configuration/pages/edp-gitserver-list/providers/DynamicData/provider.tsx, src/pages/edp-configuration/pages/edp-gitserver-list/providers/DynamicData/types.ts, src/pages/edp-configuration/pages/edp-gitserver-list/view.tsx, src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageGitServer/components/GitServer/components/fields/OverrideWebHookURL/index.tsx, src/widgets/ManageGitServer/components/GitServer/components/fields/UserName/SSHPort/index.tsx, src/widgets/ManageGitServer/components/GitServer/components/fields/WebHookURL/index.tsx, src/widgets/ManageGitServer/components/GitServer/components/fields/index.ts, src/widgets/ManageGitServer/components/GitServer/index.tsx, src/widgets/ManageGitServer/hooks/useGitServerCreateForm.ts, src/widgets/ManageGitServer/hooks/useGitServerEditForm.ts, src/widgets/ManageGitServer/index.create.test.tsx, src/widgets/ManageGitServer/index.edit.test.tsx, src/widgets/ManageGitServer/index.tsx, src/widgets/ManageGitServer/names.ts, src/widgets/ManageGitServer/types.ts, src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageRegistry/components/ConfigMap/fields/RegistryEndpoint/index.tsx, src/widgets/ManageRegistry/components/ConfigMap/fields/RegistrySpace/index.tsx, src/widgets/PipelineRunGraph/hooks/usePipelineRunGraphData.ts
- Add override webhook url checkbox and webhook url fields in git server form
- add regexp pattern for registry space field in registry form
- update labels for ghcr registry flow
- disable registry endpoint for ghcr registry flow
=> feat: Update GitServer form (#242)

src/components/ActionsInlineList/index.tsx, src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/hooks/useTabs.tsx, src/pages/edp-pipeline-details/view.tsx, src/widgets/LogViewer/index.tsx, src/widgets/PipelineRunActionsMenu/index.tsx, src/widgets/PipelineRunList/components/DeleteDialog/index.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx, src/widgets/PipelineRunList/index.tsx
- Add updated at, duration, started at fields into pipeline page
- Add started at, duration fields into pipelines table 
- Remove follow option to fix logs blinking
- Fix selected list cleaning after pipelines deletion
- Automatically change pod container on step change
- Add labels for action buttons
- Navigate user back to pipelines page after pipeline deletion
=> feat: Update pipeline page

src/pages/edp-stage-details/components/Applications/index.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx
- update deploy btn logic. It can be enabled only when all stage apps are selected and all their image tags are set
=> fix: Enable deploy btn when all apps are selected

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, SECURITY.md, pull_request_template.md
This Pull Request introduces a set of community health files to the repository, aiming to enhance the contribution experience, establish a code of conduct, provide clear guidelines for reporting security vulnerabilities, and streamline the feature request and bug reporting processes. These changes are crucial for fostering a welcoming and productive community environment around the EDP Headlamp project.
Testing for this kind of contribution mainly revolves around proofreading and ensuring that all links are correct and accessible. Each document was reviewed for clarity, relevance, and adherence to the project's standards. No automated tests are applicable for these changes.
=> feat: Add pull request templates for github issues(#234)

src/components/ErrorContent/index.tsx, src/components/LogViewer/index.tsx, src/components/TileChart/index.tsx, src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/hooks/useTabs.tsx, src/pages/edp-stage-details/components/Applications/components/ValuesOverrideCheckbox/index.tsx, src/pages/edp-stage-details/components/Applications/hooks/useUpperColumns.tsx, src/pages/edp-stage-details/components/Applications/index.tsx, src/widgets/ManageGitServer/components/GitServer/components/fields/OverrideWebHookURL/index.tsx, src/widgets/ManageGitServer/hooks/useGitServerEditForm.ts, src/widgets/ManageRegistry/components/ConfigMap/fields/RegistrySpace/index.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx
- Update error message component
- Fix values override all switch functionality to be synced with other switches 
- Fix webhook url field in git server form
- Fix registry space regexp
- Fix typography in logviewer component
Fixes #247
=> feat: Update warning messages and bugfixes

src/components/ButtonWithPermission/index.tsx, src/pages/edp-cdpipeline-details/components/StageListFilter/index.tsx, src/pages/edp-cdpipeline-list/view.tsx, src/pages/edp-component-details/components/CodebaseBranchesList/components/TableHeaderActions/index.tsx, src/pages/edp-component-list/components/ComponentListFilter/index.tsx, src/pages/edp-configuration/pages/edp-quick-link-list/view.tsx, src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRun/index.tsx, src/pages/edp-pipelines/components/PipelineRunList/index.tsx, src/pages/edp-pipelines/constants.ts, src/pages/edp-stage-details/components/Applications/index.tsx, src/utils/actions/createKubeAction/index.ts, src/widgets/CDPipelineActionsMenu/index.tsx, src/widgets/CodebaseActionsMenu/index.tsx, src/widgets/CodebaseBranchActions/index.tsx, src/widgets/ManageRegistry/components/ConfigMap/fields/RegistryEndpoint/index.tsx, src/widgets/PipelineRunActionsMenu/index.tsx, src/widgets/QuickLinkActionsMenu/index.tsx, src/widgets/StageActionsMenu/index.tsx, src/widgets/StageActionsMenu/utils.ts
- Fix permissions check related issues
- Fix registry form registry endpoint field value form sync issues
- Fix crashes in pipeline page
- Fix delete button logic in deploy flow
- Fix pipelines page crash when trying to filter by labels
Fixes #249
=> fix: Permission check fixes, pipeline fixes, crash fixes

Dockerfile, src/pages/edp-component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/pages/edp-component-details/components/Overview/index.tsx, src/pages/edp-component-details/page.tsx, src/pages/edp-component-details/providers/Data/provider.tsx, src/pages/edp-component-details/view.tsx, src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/hooks/useTabs.tsx, src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/index.tsx, src/services/link-creation/sonar/index.test.ts, src/services/link-creation/sonar/index.ts, src/widgets/SonarQubeMetrics/index.tsx, src/widgets/SonarQubeMetrics/types.ts
- Hide version,build,successful build values in branch if edp versioning
- Make logs tab to be default one when clicking task run step tab in pipeline page
- Add open in git button in component page
- Update sonar api url(add defaultbranch)
- Update headlamp image
=> fix: Fix various ui ux issues (#254)

deploy-templates/templates/route.yaml
=> chore: Remove status field from route

src/components/InfoColumns/index.tsx, src/pages/edp-stage-details/components/Applications/components/ImageStreamTagsSelect/index.tsx, src/pages/edp-stage-details/components/Applications/components/ImageStreamTagsSelect/types.ts, src/pages/edp-stage-details/components/Applications/hooks/useButtonsEnabled.ts, src/pages/edp-stage-details/components/Applications/hooks/useColumns.tsx, src/pages/edp-stage-details/components/Applications/hooks/useConfigurationHandlers.ts, src/pages/edp-stage-details/components/Applications/index.tsx, src/pages/edp-stage-details/components/ApplicationsWrapper/index.tsx, src/providers/Filter/components/Filter/index.tsx, src/providers/Form/index.tsx, src/widgets/CreateCodebaseFromTemplate/components/fields/GitUrlPath/index.tsx, src/widgets/CreateEditCodebase/components/fields/GitUrlPath/index.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx
Fix ingress field:
Add repository path validation:
Add previous deployed version:
Improve values override flag (enable without page refresh):
Fix Git URL Path:
Fix links:
Disable 'DELETE' button if pipeline in 'running' state:
Fixes #258
=> fix: App improvements and fixes

src/pages/edp-pipelines/components/PipelineRunList/index.tsx
=> fix: Fix filter fields alignment 

src/k8s/Application/hooks/useStreamApplicationListByPipelineStageLabel.tsx, src/pages/edp-stage-details/hooks/useEnrichedApplicationsWithArgoApplication.ts, src/pages/edp-stage-details/hooks/usePageTabs.tsx, src/providers/Form/index.tsx, src/widgets/AIChat/index.tsx, src/widgets/ManageCodeMie/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageCodeMie/__snapshots__/index.read.test.tsx.snap, src/widgets/ManageCodeMie/components/QuickLink/index.tsx, src/widgets/ManageCodeMie/index.read.test.tsx
Fix values override default value in stage deploy table
Fixes # (issue)
=> fix: Fix values override default value 

src/widgets/AIChat/components/Chat/index.tsx, src/widgets/AIChat/hooks/useStreaming.ts, src/widgets/AIChat/index.tsx, src/widgets/AIChat/types.ts
Fix codemie server response parsing
Fixes #273
=> fix: Update codemie chat response

src/providers/Form/components/FormAutocomplete/index.tsx, src/providers/Form/components/FormAutocomplete/types.ts, src/widgets/CreateEditCDPipeline/__snapshots__/index.edit.test.tsx.snap, src/widgets/CreateEditCDPipeline/components/Create/components/FormActions/index.tsx, src/widgets/CreateEditCDPipeline/components/fields/Applications/components/ApplicationRow/index.tsx, src/widgets/CreateEditCDPipeline/components/fields/Applications/index.tsx
Update applications field in Environment creation, changing field type from "select" to "autocomplete". 
Add reusable FormAutocomplete component for future use.
Fixes #284
=> feat: Update apps field in env creation

README.md, package-lock.json, package.json, src/constants/urls.ts, src/widgets/CreateCodebaseBranch/__snapshots__/index.test.tsx.snap, src/widgets/CreateEditCDPipeline/__snapshots__/index.create.test.tsx.snap, src/widgets/CreateEditCDPipeline/__snapshots__/index.edit.test.tsx.snap, src/widgets/CreateEditCodebase/__snapshots__/index.edit.test.tsx.snap, src/widgets/CreateEditStage/__snapshots__/index.create.test.tsx.snap, src/widgets/CreateEditStage/__snapshots__/index.edit.test.tsx.snap, src/widgets/HelpMenu/menu.ts
Point to new documentation domain
Fixes #288 
=> chore: Update links to new documentation location (#288)

Dockerfile
Update headlamp version
Fixes #291
=> feat: Add err msg in create modal

src/pages/edp-cdpipeline-list/components/CDPipelineList/index.tsx, src/pages/edp-configuration/components/ConfigurationPageContent/index.tsx, src/pages/edp-configuration/constants.ts, src/pages/edp-configuration/pages/edp-argocd-integration/page.tsx, src/pages/edp-configuration/pages/edp-cluster-list/page.tsx, src/pages/edp-configuration/pages/edp-codemie-integration/page.tsx, src/pages/edp-configuration/pages/edp-defect-dojo-integration/page.tsx, src/pages/edp-configuration/pages/edp-dependency-track-integration/page.tsx, src/pages/edp-configuration/pages/edp-gitops/page.tsx, src/pages/edp-configuration/pages/edp-gitserver-list/page.tsx, src/pages/edp-configuration/pages/edp-jira-integration/page.tsx, src/pages/edp-configuration/pages/edp-nexus-integration/page.tsx, src/pages/edp-configuration/pages/edp-registry-list/page.tsx, src/pages/edp-configuration/pages/edp-sonar-integration/page.tsx, src/pages/edp-configuration/pages/edp-sso-integration/page.tsx, src/pages/edp-configuration/providers/Permissions/context.ts, src/pages/edp-configuration/providers/Permissions/hooks.ts, src/pages/edp-configuration/providers/Permissions/provider.tsx, src/pages/edp-configuration/providers/Permissions/types.ts, src/pages/edp-overview-list/components/ComponentList/components/AddNewQuickLinkCard/index.tsx, src/pages/edp-pipeline-details/components/PipelineRunDetails/components/TaskRunStep/index.tsx
Add permissions checks in configuration pages and etc 
Fix crash in failed pipeline page
Fixes #293
=> feat: Add permissions checks in cfg pages

src/widgets/AIChat/components/Chat/index.tsx, src/widgets/AIChat/components/ChatHistory/index.tsx, src/widgets/AIChat/components/ChatHistory/types.ts, src/widgets/AIChat/components/Message/styles.ts, src/widgets/AIChat/hooks/useStreaming.ts, src/widgets/AIChat/index.tsx, src/widgets/AIChat/styles.ts, src/widgets/AIChat/types.ts, src/widgets/AIChat/utils.ts
Update chat logic to handle different response format from codemie api
Fixes #295
=> feat: Update chat logic

Dockerfile, src/pages/edp-configuration/pages/edp-gitops/constants.ts, src/pages/edp-configuration/pages/edp-gitops/page.tsx, src/pages/edp-configuration/pages/edp-gitops/providers/Permissions/context.ts, src/pages/edp-configuration/pages/edp-gitops/providers/Permissions/hooks.ts, src/pages/edp-configuration/pages/edp-gitops/providers/Permissions/provider.tsx, src/pages/edp-configuration/pages/edp-gitops/providers/Permissions/types.ts, src/pages/edp-configuration/pages/edp-gitops/view.tsx, src/pages/edp-configuration/pages/edp-jira-integration/view.tsx, src/widgets/ManageJiraServer/hooks/useJiraServerCreateForm.ts, src/widgets/ManageJiraServer/hooks/useJiraServerEditForm.ts, src/widgets/ManageJiraServer/index.tsx
Fix issues after review:
- Modal didn't close on success
- GitOps page didn't have permission check on empty text user friendly button
- Unset namespace notification appeared on login page
Fixes #297
=> fix: Fix issues after review

src/pages/edp-stage-details/components/Applications/hooks/useColumns.tsx
=> chore: Update information label for values override (#298)

Dockerfile, src/k8s/TaskRun/index.ts, src/pages/edp-configuration/pages/edp-sso-integration/view.tsx
- Rename Create / Apply into Create / Apply Resource in EditorDialog
- Fix Incorrect Display of Current Running Step in Pipeline Page
- Fix Error on Configuration->Access Page: TypeError with 'nginx.ingress.kubernetes.io/auth-url'
Fixes #302
=> fix: Fix issues

src/k8s/PipelineRun/utils/getPullRequestURL/index.test.ts, src/k8s/PipelineRun/utils/getPullRequestURL/index.ts, src/pages/edp-cdpipeline-list/view.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx
Add PR/MR column into PipelineRuns table
Fixes #304
=> feat: Add pull request link

src/k8s/PipelineRun/utils/getPullRequestURL/index.ts
Fix pipeline page crash when pipeline run has no params at the moment
Fixes #304 
=> fix: Fix pipeline crash when no params

src/constants/pipelineTypes.ts, src/k8s/groups/EDP/Stage/types.ts, src/k8s/groups/Tekton/PipelineRun/hooks/useCreateCleanPipelineRun.ts, src/k8s/groups/Tekton/TriggerTemplate/hooks/useCleanTriggerTemplateListQuery.ts, src/pages/configuration/pages/codemie/view.tsx, src/pages/pipelines/components/PipelineRunList/index.tsx, src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts, src/pages/stage-details/components/Applications/index.tsx, src/pages/stage-details/components/Applications/types.ts, src/pages/stage-details/components/ApplicationsWrapper/index.tsx, src/pages/stage-details/hooks/useInfoColumns.tsx, src/pages/stage-details/hooks/usePageTabs.tsx, src/pages/stage-details/providers/DynamicData/context.ts, src/pages/stage-details/providers/DynamicData/provider.tsx, src/pages/stage-details/providers/DynamicData/types.ts, src/providers/Dialog/mapping.tsx, src/utils/formFieldValidation.ts, src/widgets/ConfirmModal/constants.ts, src/widgets/ConfirmModal/index.tsx, src/widgets/ConfirmModal/types.ts, src/widgets/CreateEditStage/__snapshots__/index.create.test.tsx.snap, src/widgets/CreateEditStage/__snapshots__/index.edit.test.tsx.snap, src/widgets/CreateEditStage/components/Create/components/Form/index.tsx, src/widgets/CreateEditStage/components/Edit/components/Form/index.tsx, src/widgets/CreateEditStage/components/Edit/hooks/useDefaultValues.ts, src/widgets/CreateEditStage/components/fields/CleanTemplate/index.tsx, src/widgets/CreateEditStage/components/fields/DeployTemplate/index.tsx, src/widgets/CreateEditStage/components/fields/index.ts, src/widgets/CreateEditStage/names.ts, src/widgets/ManageCodeMie/hooks/useCodemieProjectEditForm.ts
Add environment cleanup behaviour
Fixes #317 
=> feat: Add clean env behaviour

.github/workflows/release.yaml, README.md, deploy-templates/Chart.yaml, deploy-templates/README.md, deploy-templates/values.yaml
Renamed the EDP name matches to KubeRocketCI and updated the documentation links.
Fixes #325 
=> chore: Update KubeRocketCI names and documentation links (#325)

src/k8s/groups/EDP/CodemieProjectSettings/constants.ts, src/k8s/groups/EDP/CodemieProjectSettings/index.ts, src/k8s/groups/EDP/CodemieProjectSettings/types.ts, src/pages/configuration/pages/codemie/view.tsx, src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts, src/widgets/PipelineRunList/index.tsx
Fix pipelines filter
Add error notification if clean pipeline run template is not found when trying to create clean pipeline run
Add CodemieProjectSettings status and fix markup
Fixes #327 
=> fix: Fix bugs on pipelines page

src/k8s/groups/default/Secret/utils/createChatAssistantIntegrationSecretInstance/index.test.ts, src/k8s/groups/default/Secret/utils/createChatAssistantIntegrationSecretInstance/index.ts, src/widgets/AIChat/components/Chat/index.tsx, src/widgets/AIChat/utils/sanitizeMessage.ts
Add more rules for sanitizing codemie stream html output
Fixes #331 
=> fix: Sanitize CodeMie html

src/k8s/groups/EDP/Codemie/index.ts, src/k8s/groups/EDP/Codemie/types.ts, src/pages/cdpipeline-details/components/StageList/index.tsx, src/pages/cdpipeline-details/components/StageListFilter/index.tsx, src/pages/cdpipeline-details/route.tsx, src/pages/cdpipeline-details/view.tsx, src/pages/cdpipeline-list/components/CDPipelineList/index.tsx, src/pages/cdpipeline-list/route.tsx, src/pages/cdpipeline-list/view.tsx, src/pages/overview-list/components/CDPipelinesGraph/index.tsx, src/pages/overview-list/components/StagesGraph/index.tsx, src/pages/stage-details/components/Applications/hooks/useColumns.tsx, src/pages/stage-details/route.tsx, src/pages/stage-details/view.tsx, src/routes/names.ts, src/routes/sidebar-list.ts, src/widgets/CreateEditCDPipeline/__snapshots__/index.create.test.tsx.snap, src/widgets/CreateEditCDPipeline/components/Create/components/DialogHeader/index.tsx, src/widgets/CreateEditCDPipeline/components/Create/components/FormActions/index.tsx, src/widgets/CreateEditCDPipeline/components/fields/Applications/index.tsx, src/widgets/CreateEditCodebase/components/fields/CodemieIntegration/index.tsx, src/widgets/CreateEditStage/__snapshots__/index.create.test.tsx.snap, src/widgets/CreateEditStage/components/Create/components/DialogHeader/index.tsx, src/widgets/CreateEditStage/components/fields/StageName/index.tsx
Update Environment/Stage labels to Deployment Flow/Environment within whole application
Fixes #333 
=> feat: Update labels

src/widgets/PipelineRunList/constants.ts
Update pipelines filter
Fixes #337 
=> fix: Update pipelines filter

src/k8s/groups/EDP/CodemieApplication/config.ts, src/k8s/groups/EDP/CodemieApplication/constants.ts, src/k8s/groups/EDP/CodemieApplication/index.ts, src/k8s/groups/EDP/CodemieApplication/types.ts, src/pages/configuration/pages/codemie/providers/DynamicData/context.ts, src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx, src/pages/configuration/pages/codemie/providers/DynamicData/types.ts, src/pages/configuration/pages/codemie/view.tsx
Add codemie applications list into codemie section
Fixes #342 
=> feat: Add codemie applications

Dockerfile
Update Dockerfile base image to address libssl3 vulnerability.
Fixes #346 
=> chore: Update Dockerfile base image (#346)

src/widgets/dialogs/ManageStage/__snapshots__/index.test.tsx.snap, src/widgets/dialogs/ManageStage/components/fields/CleanTemplate/index.tsx, src/widgets/dialogs/ManageStage/components/fields/DeployTemplate/index.tsx
Fix case when chosen trigger template refers to nonexistant pipeline
Fixes #351 
=> fix: Fix nonexistant pipeline diagram btn

src/components/Table/components/TableHead/components/TableRow/index.tsx, src/components/Table/components/TableHead/components/TableRow/types.ts, src/components/Table/components/TableHead/index.tsx, src/components/Table/components/TableHead/types.ts, src/components/Table/hooks/useReadyData.ts, src/components/Table/index.tsx, src/components/Table/types.ts, src/components/Table/utils.ts, src/pages/configuration/pages/pipeline-list/page.tsx, src/pages/configuration/pages/task-list/page.tsx, src/providers/Form/components/FormAutocompleteSingle/index.tsx, src/providers/Form/components/FormAutocompleteSingle/types.ts, src/widgets/PipelineList/hooks/useColumns.tsx, src/widgets/PipelineList/index.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx, src/widgets/TaskList/hooks/useColumns.tsx, src/widgets/TaskList/index.tsx, src/widgets/dialogs/ManageCodebaseBranch/__snapshots__/index.test.tsx.snap, src/widgets/dialogs/ManageCodebaseBranch/components/fields/BuildPipeline/index.tsx, src/widgets/dialogs/ManageCodebaseBranch/components/fields/ReviewPipeline/index.tsx
- Add custom sort function functionality in tables
- Add task description in task list table
- Add task/pipeline sorting 
- Add task/pipeline search
- Update codebase branch build and review pipelines fields to be single autocomplete with ability to search options
Fixes #361 
=> feat: Add table custom sort

src/constants/deploymentScripts.ts, src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/components/Advanced/index.tsx, src/widgets/dialogs/ManageCodebase/components/fields/DeploymentScript/index.tsx, src/widgets/dialogs/ManageCodebase/components/fields/index.ts
Add ability for user to select deployment script between "helm-chat" and "rpm-package"
Fixes #363 
=> feat: Add deployment script select

src/providers/Form/index.tsx, src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/components/Advanced/index.tsx, src/widgets/dialogs/ManageCodebase/components/fields/DeploymentScript/index.tsx, src/widgets/dialogs/ManageStage/components/Create/components/FormActions/index.tsx, src/widgets/dialogs/ManageStage/components/Create/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageStage/components/fields/CleanTemplate/index.tsx, src/widgets/dialogs/ManageStage/components/fields/DeployTemplate/index.tsx, src/widgets/dialogs/ManageStage/components/fields/StageName/index.tsx, src/widgets/dialogs/ManageStage/constants.ts, src/widgets/dialogs/ManageStage/names.ts, src/widgets/dialogs/ManageStage/providers/CurrentDialog/context.ts, src/widgets/dialogs/ManageStage/providers/CurrentDialog/provider.tsx, src/widgets/dialogs/ManageStage/providers/CurrentDialog/types.ts
- Add in-between stepper steps form fields validation
- Add default values for clean, deploy pipelines
- Update deploymentscript field value tooltip
Fixes # (issue)
=> feat: Update env creation

src/components/Tabs/index.tsx, src/components/Tabs/styles.ts, src/components/Tabs/types.ts, src/k8s/groups/Tekton/PipelineRun/index.ts, src/k8s/groups/Tekton/PipelineRun/types.ts, src/pages/stage-details/hooks/usePageTabs.tsx, src/pages/stage-details/providers/DynamicData/context.ts, src/pages/stage-details/providers/DynamicData/provider.tsx, src/pages/stage-details/providers/DynamicData/types.ts, src/widgets/PipelineRunList/hooks/useColumns.tsx
Highlight pipelines tab in stage page when new pipeline runs are created when user is on page
Fixes #369 
=> feat: Highlight pipelines tab

src/widgets/PipelineRunList/components/Actions/index.tsx
Fix pipeline run actions menu
Fixes #369 
=> fix: Fix pipeline actions

Dockerfile
Fix username get crash
Fixes #372 
=> fix: Fix username get crash

README.md, docs/README.md
=> chore: Re-structure documentation assets (#375)

src/components/PageLogicWrapper/index.tsx, src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/TaskRun/hooks/useTabs.tsx, src/pages/pipelines/view.tsx, src/providers/Permissions/context.ts, src/providers/Permissions/provider.tsx, src/widgets/PipelineRunActionsMenu/index.tsx
Cache permissions with 1 minute cacheTime
Fixes #378 
=> feat: Cache permissions

CHANGELOG.md
This change updates the CHANGELOG.md file with the contents generated by the "make changelog" command.
=> docs: Update CHANGELOG.md file (#382)

src/widgets/PipelineList/hooks/useColumns.tsx, src/widgets/dialogs/ManageCDPipeline/components/fields/PipelineName/index.tsx
- Add pipeline description column
- Add validation when creating deployment flow for name field
Fixes #386 
=> feat: Add description column and validation

src/providers/Form/components/FormAutocomplete/index.tsx, src/providers/Form/components/FormAutocompleteSingle/index.tsx, src/utils/sort/sortKubeObjectsByCreationTimestamp/index.ts, src/widgets/dialogs/ManageCDPipeline/__snapshots__/index.test.tsx.snap, src/widgets/dialogs/ManageCDPipeline/components/Create/components/FormActions/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/Create/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageCDPipeline/components/Edit/components/FormActions/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/Edit/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/components/ApplicationRow/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/components/ApplicationRow/types.ts, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/constants.ts, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/index.tsx, src/widgets/dialogs/ManageCDPipeline/index.test.tsx, src/widgets/dialogs/ManageCDPipeline/names.ts, src/widgets/dialogs/ManageCDPipeline/providers/CurrentDialog/context.ts, src/widgets/dialogs/ManageCDPipeline/providers/CurrentDialog/provider.tsx, src/widgets/dialogs/ManageCDPipeline/providers/CurrentDialog/types.ts, src/widgets/dialogs/ManageCodebaseBranch/__snapshots__/index.test.tsx.snap
Update deployment flow creation/edit:
- Add autocomplete when choosing branch
- Refactor autocomplete single and multiple logic throughout application
- Refactor applications add/remove logic 
Fixes #393 
=> feat: Update applications add and remove

Dockerfile
Update image version after update #395 
Fixes #395
=> chore: Update image version

src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/pages/stage-details/components/Variables/index.tsx, src/pages/stage-details/hooks/usePageTabs.tsx, src/pages/stage-details/providers/DynamicData/context.ts, src/pages/stage-details/providers/DynamicData/provider.tsx, src/pages/stage-details/providers/DynamicData/types.ts
=> feat: Add env variables section

CHANGELOG.md
This change updates the CHANGELOG.md file
=> docs: Update changelog file for release notes (#382)

src/pages/stage-details/components/Variables/index.tsx, src/pages/stage-details/hooks/usePageTabs.tsx, src/pages/stage-details/providers/DynamicData/context.ts, src/pages/stage-details/providers/DynamicData/provider.tsx, src/pages/stage-details/providers/DynamicData/types.ts
=> feat: Update env variables to use configmap

src/widgets/dialogs/ManageCDPipeline/components/Edit/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/components/ApplicationRow/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/index.tsx
Fix to promote default values in create/edit deployment flow
Fixes #414 
=> fix: Fix to promote default values

Dockerfile, src/pages/cdpipeline-list/view.tsx
Try fix redirect after auth 
Fixes #418 
=> fix: Try fix redirect after auth

Dockerfile
Fix redirect after auth 
Fixes #419 
=> fix: Fix redirect after auth

src/k8s/groups/Tekton/PipelineRun/hooks/useCreateBuildPipelineRun.ts, src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.test.ts, src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/widgets/PipelineRunList/components/DeleteDialog/index.tsx
Fix pipelines multi deletion and fix build pipeline creation
Fixes #421 
=> fix: Fix pipelines 

src/configs/select-options/triggerTypes.ts, src/constants/triggerTypes.ts, src/icons/iconify-icons-mapping.ts, src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/ChoiceButtonGroup/index.tsx, src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/CommentDialog/constants.ts, src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/CommentDialog/index.tsx, src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/CommentDialog/types.ts, src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/index.tsx, src/widgets/dialogs/ManageCDPipeline/providers/CurrentDialog/provider.tsx
- Update approve/reject with additional commentary with a reason of approving/rejecting
- Add 'auto-stable' trigger type option
- Remove caching of applications in deployment flow
Fixes #423 
=> feat: Update approve reject

Dockerfile, src/widgets/ManageRegistry/hooks/useConfigMapEditForm.ts, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/components/ApplicationRow/index.tsx
- Fix login redirect issue when user stays on login page forever if his initial page location is login page
- Fix app crashing when adding application with no branches when creating deployment flow
- Fix inability to change registry type when creating new registry integration
Fixes #425
=> fix: No branch crash, registry create, login redirect 

src/components/PageLogicWrapper/index.tsx
=> fix: Requests caching

src/pages/component-details/providers/Data/provider.tsx, src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/index.tsx, src/services/api/index.ts
- Add krakend backend integration for further sonar/deptrack widgets data consuming
- Fix requests caching
Fixes #427 
=> feat: Add krakend backend integration

src/providers/Form/components/FormSwitch/index.tsx, src/providers/Form/components/FormSwitch/types.ts, src/services/api/index.ts, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/components/ApplicationRow/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/index.tsx, src/widgets/dialogs/ManageCDPipeline/names.ts
=> feat: Update deployment flow promote

src/widgets/dialogs/ManageCDPipeline/components/Create/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageCDPipeline/components/Edit/hooks/useDefaultValues.ts
Fix to promote default value for create/edit modes
Fixes #432 
=> fix: To promote default value 

src/widgets/dialogs/CreateCodebaseFromTemplate/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageCodebase/components/Create/hooks/useDefaultValues.ts
Set EDP as default versioning type when creating component
Fixes #437 
=> feat: Set edp as default versioning type

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md, package-lock.json, package.json
=> chore: Update current development version (#439)

src/widgets/ManageGitServer/components/GitServer/components/fields/Name/index.tsx
=> fix: Add validation for name field

src/pages/stage-details/components/Applications/components/ImageStreamTagsSelect/index.tsx, src/pages/stage-details/providers/DynamicData/provider.tsx, src/providers/Form/components/FormSelect/index.tsx, src/providers/Form/components/FormSelect/types.ts
- Improve applications table update logic
- Add user-friendly helper text indicating that there is a need to produce at least one pipeline run to see any image tags available
Fixes #443 
=> feat: Improve applications table update

src/k8s/groups/default/Pod/config.ts, src/k8s/groups/default/Pod/index.ts, src/k8s/groups/default/Pod/types.ts, src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/index.tsx, src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/types.ts, src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx, src/pages/stage-details/components/Applications/hooks/useColumns.tsx, src/pages/stage-details/providers/DynamicData/context.ts, src/pages/stage-details/providers/DynamicData/provider.tsx, src/pages/stage-details/providers/DynamicData/types.ts, src/widgets/dialogs/PodsLogViewer/index.tsx, src/widgets/dialogs/PodsLogViewer/types.ts, src/widgets/dialogs/PodsTerminal/index.tsx, src/widgets/dialogs/PodsTerminal/types.ts
Improve pods features such as pod logs and terminal:
- Add init containers
- Disable buttons if no pods for specific argo app not found
Fixes #445 
=> feat: Improve pods features

pull_request_template.md
Updated the Pull Request template to include "Enhancement" as a new change type.
Fixes #234
=> chore: Update Pull Request Template (#234)

src/pages/stage-details/components/Applications/components/ImageStreamTagsSelect/index.tsx
Show version diff marker in deployment
Fixes #450 
=> feat: Show version diff marker

deploy-templates/README.md, deploy-templates/templates/deployment.yaml, deploy-templates/values.yaml
Implement OIDC integration with Microsoft Entra identity provider.
Fixes #454
=> feat: Implement OIDC integration with Microsoft Entra IdP (#454)

src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/ChoiceButtonGroup/index.tsx, src/pages/pipeline-details/constants.ts
Add permission check for approve/reject buttons in pipeline page
Fixes #456 
=> feat: Add permission check for approve button

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md, package-lock.json, package.json
=> chore: Update current development version (#458)

src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.test.ts, src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.ts, src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.test.ts, src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.ts, src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts
Update and refactor clean/deploy pipeline creation
Fixes #463 
=> feat: Update clean deploy pipeline creation 

src/providers/Form/components/FormTextFieldPassword/index.tsx, src/widgets/ManageArgoCD/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageArgoCD/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageArgoCD/__snapshots__/index.read.test.tsx.snap, src/widgets/ManageChatAssistant/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageChatAssistant/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageChatAssistant/__snapshots__/index.read.test.tsx.snap, src/widgets/ManageClusterSecret/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageClusterSecret/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageDefectDojo/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageDefectDojo/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageDefectDojo/__snapshots__/index.read.test.tsx.snap, src/widgets/ManageDependencyTrack/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageDependencyTrack/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageDependencyTrack/__snapshots__/index.read.test.tsx.snap, src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageJiraServer/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageJiraServer/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageJiraServer/__snapshots__/index.read.test.tsx.snap, src/widgets/ManageNexus/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageNexus/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageNexus/__snapshots__/index.read.test.tsx.snap, src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageSonar/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageSonar/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageSonar/__snapshots__/index.read.test.tsx.snap
Remove input type password autocomplete
Fixes #465 
=> feat: Remove type password fields autocomplete 

Dockerfile
Open openshift auth in new tab
Fixes #469 
=> feat: Open auth in new tab

src/services/link-creation/kibana/index.test.ts, src/services/link-creation/kibana/index.ts
Fix kubernetes namespace name substring from "kubernetes_namespace_name" to "kubernetes.namespace_name"
Fixes #473 
=> fix: Kibana link

src/services/link-creation/kibana/index.test.ts, src/services/link-creation/kibana/index.ts
Update columns:message to columns:log
Fixes #473 
=> fix: Update kibana link

Dockerfile, src/pages/pipeline-details/components/Details/components/TaskRunStepWrapper/hooks/useTabs.tsx, src/widgets/PodsLogViewer/index.tsx, src/widgets/PodsLogViewer/types.ts
Fix logs rerendering
Fixes #478 
=> fix: Logs rerendering and getLogs fn 

src/k8s/groups/EDP/Codebase/hooks/useEnrichedApplicationsWithImageStreamsQuery.ts, src/pages/cdpipeline-details/providers/DynamicData/provider.tsx, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/pages/component-details/components/CodebaseBranchesList/index.tsx, src/pages/component-details/hooks/usePageTabs.tsx, src/pages/component-details/providers/Data/provider.tsx, src/pages/component-details/providers/DynamicData/context.ts, src/pages/component-details/providers/DynamicData/provider.tsx, src/pages/component-details/providers/DynamicData/types.ts, src/pages/component-details/utils.ts, src/pages/configuration/pages/argocd/view.tsx, src/pages/configuration/pages/chat-assistant/view.tsx, src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx, src/pages/configuration/pages/defect-dojo/view.tsx, src/pages/configuration/pages/dependency-track/view.tsx, src/pages/configuration/pages/gitops/view.tsx, src/pages/configuration/pages/gitservers/providers/DynamicData/provider.tsx, src/pages/configuration/pages/jira/view.tsx, src/pages/configuration/pages/nexus/view.tsx, src/pages/configuration/pages/registry/providers/DynamicData/provider.tsx, src/pages/configuration/pages/sonar/view.tsx, src/pages/pipeline-details/providers/DynamicData/provider.tsx, src/pages/stage-details/providers/DynamicData/provider.tsx, src/widgets/AIChat/index.tsx
Fix page loadings
Fix pipeline page crash where there's no approval task cr/crd. 
Fixes #481 
=> fix: Page loadings

src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Actions/index.tsx, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Actions/types.ts, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/types.ts, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/index.tsx, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/types.ts, src/pages/component-details/components/CodebaseBranchesList/index.tsx, src/pages/component-details/providers/DynamicData/context.ts, src/pages/component-details/providers/DynamicData/provider.tsx, src/pages/component-details/providers/DynamicData/types.ts, src/pages/pipeline-details/components/Details/components/TaskRunStepWrapper/hooks/useTabs.tsx, src/pages/pipeline-details/page.tsx, src/pages/stage-details/view.tsx, src/providers/Tabs/hooks.ts, src/services/link-creation/git/index.ts, src/widgets/PipelineRunActionsMenu/components/CustomActionsInlineList/index.tsx, src/widgets/PodsLogViewer/types.ts
Fixes:
When navigating through pipeline steps, pod's container value is not updating
When navigation to component page user can encounter crash when gitServer is not yet loaded. Also, refactor component page components to reduce prop drilling and use context 
Fixes #485 
=> fix: Bugs after latest update 

src/pages/component-details/components/CodebaseBranchesList/index.tsx
Fix edit branch crash when getting branch "name" field value
Fixes #487 
=> fix: Edit branch 

src/components/TileChart/index.tsx, src/index.tsx, src/k8s/groups/default/ResourceQuota/config.ts, src/k8s/groups/default/ResourceQuota/index.ts, src/k8s/groups/default/ResourceQuota/labels.ts, src/k8s/groups/default/ResourceQuota/types.ts, src/widgets/ResourceQuotas/components/CircleProgress/index.tsx, src/widgets/ResourceQuotas/components/CircleProgress/types.ts, src/widgets/ResourceQuotas/index.tsx, src/widgets/ResourceQuotas/types.ts, src/widgets/ResourceQuotas/utils.ts
Add resource quotas widget in top bar
Fixes #489 
=> feat: Add resource quotas widget

src/widgets/dialogs/ManageStage/components/fields/QualityGates/components/QualityGateRow/index.tsx, src/widgets/dialogs/ManageStage/components/fields/QualityGates/constants.ts
Hide manual Quality Gate step name field
Fixes #496 
=> feat: Hide manual qg name field

src/pages/stage-details/components/Variables/index.tsx
Add test attributes for buttons in variables form for ui testing purposes
Fixes #501 
=> feat: Add test attrs in variables form

src/k8s/groups/default/ResourceQuota/index.ts, src/k8s/groups/default/ResourceQuota/types.ts, src/widgets/ResourceQuotas/components/RQItem/index.tsx, src/widgets/ResourceQuotas/index.tsx
Add deployment flow RQs info in Resource Quotas widget
Fixes #503 
=> feat: Add deployment flow RQs (#503)

src/components/ErrorContent/index.tsx, src/k8s/groups/Tekton/Task/index.ts, src/k8s/groups/Tekton/Task/types.ts, src/pages/pipeline-details/components/ReserveLogs/index.tsx, src/pages/pipeline-details/components/ReserveLogs/types.ts, src/pages/pipeline-details/providers/DynamicData/context.ts, src/pages/pipeline-details/providers/DynamicData/logs.query.ts, src/pages/pipeline-details/providers/DynamicData/provider.tsx, src/pages/pipeline-details/providers/DynamicData/types.ts, src/pages/pipeline-details/providers/DynamicData/utils.ts, src/pages/pipeline-details/view.tsx
Improve reserve logs(add tasks)
Fixes #505
=> feat: Improve reserve logs

Dockerfile, src/pages/component-details/view.tsx, src/pages/pipeline-details/view.tsx
Tryfix scenario when user logins via oidc with wrong credentials and gets moved to edp pages when in fact he shouldn't be able to use app.
Fixes #515 
=> fix: Try fix wrong success oidc auth

Dockerfile, src/pages/pipeline-details/view.tsx
Tryfix scenario when user logins via oidc with wrong credentials and gets moved to edp pages when in fact he shouldn't be able to use app.
Fixes #515 
=> fix: Try fix wrong success oidc auth 

Dockerfile
Tryfix scenario when user logins via oidc with wrong credentials and gets moved to edp pages when in fact he shouldn't be able to use app.
Fixes #515 
=> fix: Try fix oidc fail token

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md, package-lock.json, package.json
=> chore: Update current development version (#521)

src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.test.ts, src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts, src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/index.tsx, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/BuildGroup/index.tsx, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/BuildGroup/types.ts, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/widgets/PipelineRunActionsMenu/components/CustomActionsInlineList/index.tsx
- Add build with params option
- Add build in progress indicator on build button
- Add gitfullrepositoryname param in buildPipelineRunInstance creation
Fixes #524 
=> feat: Add build with params

src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts, src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.ts, src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.ts, src/k8s/groups/Tekton/PipelineRun/utils/createRerunPipelineRunInstance/index.ts, src/k8s/groups/default/ResourceQuota/index.ts, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/pages/component-details/components/CodebaseBranchesList/index.tsx, src/pages/pipeline-details/components/ReserveLogs/components/AllLogs/index.tsx, src/utils/truncateName.ts
Truncate PipelineRuns' names created by UI
Fixes #526 
=> feat: Truncate pipelinerun names

src/services/link-creation/git/index.test.ts, src/services/link-creation/git/index.ts
Fix bitbucket repository branch link creation
Fixes #530 
=> fix: Bitbucket repo branch link (#530)

src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.test.ts, src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts, src/k8s/groups/Tekton/PipelineRun/utils/createCleanPipelineRunInstance/index.ts, src/k8s/groups/Tekton/PipelineRun/utils/createDeployPipelineRunInstance/index.ts, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/widgets/dialogs/CreateCodebaseFromTemplate/components/fields/Name/index.tsx
- Update git-source-url field in build pipeline run creation
- Update build pipeline run creation unit tests
- Fix branch text overflow
- Fix component from template creation name field validation
Fixes #532 
=> feat: Update build git-source-url

src/k8s/groups/EDP/QuickLink/constants.ts, src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx, src/pages/stage-details/components/Monitoring/index.tsx, src/pages/stage-details/hooks/usePageTabs.tsx, src/pages/stage-details/view.tsx, src/services/link-creation/monitoring/index.test.ts, src/services/link-creation/monitoring/index.ts
Add datadog in expected monitoring providers list
Add datadog dashboard link
Disable monitoring tab if there is no monitoring quicklink
Fixes #(issue)
=> feat: Improve monitoring links

src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx, src/pages/configuration/pages/codemie/providers/DynamicData/types.ts, src/pages/configuration/pages/codemie/view.tsx, src/widgets/dialogs/ManageStage/components/fields/Cluster/index.tsx
Fix infinite loading in codemie page
Change way of getting available clusters list from listing secrets to getting the list from edp config map
Fixes #537 
=> fix: Codemie loading, available clusters list

src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx, src/pages/component-details/providers/Data/provider.tsx, src/pages/component-details/providers/Data/types.ts, src/pages/configuration/pages/codemie/view.tsx, src/pages/configuration/pages/gitops/view.tsx, src/pages/stage-details/components/Monitoring/index.tsx, src/pages/stage-details/hooks/usePageTabs.tsx, src/pages/stage-details/view.tsx, src/services/link-creation/deptrack/index.test.ts, src/services/link-creation/deptrack/index.ts, src/services/link-creation/logging/index.test.ts, src/services/link-creation/logging/index.ts, src/services/link-creation/monitoring/index.test.ts, src/services/link-creation/monitoring/index.ts, src/widgets/DeeptrackVulnerabilities/index.tsx, src/widgets/DeeptrackVulnerabilities/types.ts
Fix codemie blocks loading, error state
Fix monitoring url creation logic
Add deptrack dashboard link
Fixes #537 
=> fix: Codemie loading, monitoring url, deptrack url

Dockerfile, src/widgets/dialogs/ManageStage/components/fields/Cluster/index.tsx
Fix crash on stage create dialog
Update alert notification:
- Change request interval to 10seconds
- Show alert after 3 last unsuccessful requests
- Update alert ui
Fixes #540 
=> feat: Update alert noty

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md, package-lock.json, package.json
=> chore: Update current development version (#542)

src/components/ErrorContent/index.tsx, src/constants/urls.ts, src/pages/configuration/pages/codemie/components/Applications/index.tsx, src/pages/configuration/pages/codemie/components/Codemie/index.tsx, src/pages/configuration/pages/codemie/components/CodemieProjectSettings/index.tsx, src/pages/configuration/pages/codemie/constants.ts, src/pages/configuration/pages/codemie/providers/DynamicData/provider.tsx, src/pages/configuration/pages/codemie/view.tsx
Refactor codemie page, add "add ai assistant" doc link
Fixes #548 
=> refactor: Codemie page

src/hooks/useResourceRequestStatusMessages/index.tsx, src/k8s/groups/Tekton/PipelineRun/hooks/useCreateBuildPipelineRun.tsx, src/k8s/groups/Tekton/PipelineRun/hooks/useCreateCleanPipelineRun.tsx, src/k8s/groups/Tekton/PipelineRun/hooks/useCreateDeployPipelineRun.tsx, src/pages/cdpipeline-details/components/StageListFilter/index.tsx, src/pages/cdpipeline-details/constants.ts, src/pages/cdpipeline-details/hooks/usePageFilterContext.ts, src/pages/cdpipeline-details/types.ts, src/pages/cdpipeline-list/view.tsx, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Details/index.tsx, src/pages/component-list/components/ComponentListFilter/index.tsx, src/pages/component-list/constants.ts, src/pages/component-list/hooks/usePageFilterContext.ts, src/pages/component-list/types.ts, src/pages/configuration/pages/quicklinks/view.tsx, src/pages/marketplace/view.tsx, src/pages/stage-details/hooks/usePageTabs.tsx, src/providers/Filter/components/Filter/index.tsx, src/providers/Filter/components/Filter/types.ts, src/providers/Filter/constants.ts, src/providers/Filter/hooks.ts, src/providers/Filter/provider.tsx, src/providers/Filter/types.ts, src/services/link-creation/deptrack/index.test.ts, src/widgets/PipelineList/index.tsx, src/widgets/PipelineRunActionsMenu/index.tsx, src/widgets/PipelineRunList/constants.ts, src/widgets/PipelineRunList/index.tsx, src/widgets/PipelineRunList/types.ts, src/widgets/TaskList/index.tsx
Add search by labels
Hide filter by namespace control if allowed namespaces length is 1 or less
Fix typescript types for default and extra filter controls
Fixes #550 
=> feat: Update filter 

src/components/ResponsiveChips/index.tsx, src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx, src/pages/component-details/components/Overview/hooks/useInfoRows.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx, src/widgets/dialogs/ManageCDPipeline/__snapshots__/index.test.tsx.snap, src/widgets/dialogs/ManageCDPipeline/components/Create/components/Form/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/fields/Description/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/fields/index.ts, src/widgets/dialogs/ManageCDPipeline/names.ts
=> feat: Add CDPipeline description filed

src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx
Fix crash when CDPipeline has no description
Fixes #552 
=> fix: Undefined description crash

src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx, src/providers/Filter/constants.ts, src/widgets/PipelineList/hooks/useColumns.tsx, src/widgets/TaskList/hooks/useColumns.tsx
Fix no labels crash
Fixes #552 
=> fix: No labels crash

src/components/InfoColumns/index.tsx, src/k8s/groups/Tekton/PipelineRun/utils/createBuildPipelineRunInstance/index.ts, src/pages/component-details/providers/DynamicData/provider.tsx, src/pages/pipeline-details/components/Overview/hooks/useInfoRows.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx, src/widgets/PipelineRunResults/index.tsx
Add results column into pipeline table
Add results column into pipeline overview widget
Update review/build pipeline values in component page
Fixes #557 
=> feat: Add results column into pipeline table 

src/icons/iconify-icons-mapping.ts, src/k8s/groups/Tekton/PipelineRun/utils/getPullRequestURL/index.ts, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/BuildGroup/index.tsx, src/pages/pipeline-details/components/Details/components/TaskRunWrapper/components/CustomTaskRun/components/ChoiceButtonGroup/index.tsx, src/pages/pipeline-details/view.tsx, src/services/link-creation/git/index.test.ts, src/widgets/ManageGitOps/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageGitOps/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageGitOps/constants.ts, src/widgets/ManageGitOps/index.edit.test.tsx, src/widgets/PipelineRunActionsMenu/components/CustomActionsInlineList/index.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx, src/widgets/PipelineRunList/hooks/useUpperColumns.tsx
Add PullRequest link in Pipeline page header
Update result column (remove info icon, add dashed underline)
Update GitOps codebase name
Fix PipelineRun instance creation when CodebaseBranch is updated
Fixes #562 
=> feat: Add pr link, upd result column, upd gitops name

src/pages/component-details/providers/Data/provider.tsx, src/widgets/ManageGitOps/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageGitOps/components/Create/index.tsx, src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/hooks/useCodebaseCreationStrategies.tsx, src/widgets/dialogs/ManageCodebase/components/fields/EmptyProject/index.tsx
Add "Import" option for GitOps creation strategy
Fixes #566 
=> feat: Add import strategy for gitops create 

src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/FormActions/index.tsx
Fix clone codebase validation
Fixes #568 
=> fix: Clone codebase validation 

src/pages/pipeline-details/components/Overview/hooks/useInfoRows.tsx, src/pages/pipeline-details/hooks/useTabs.tsx
Move pipeline results to separate tab
Fixes #570 
=> feat: Move pipeline results to separate tab 

Dockerfile
=> feat: Set ns from config

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md, package-lock.json, package.json
=> chore: Update current development version (#573)

src/widgets/PipelineRunList/hooks/useColumns.tsx
=> fix: Pr link button

src/pages/pipeline-details/providers/DynamicData/logs.query.ts
Increase search horizon for logs in opensearch
Fixes #505
=> chore: Increase log search hirozon for opensearch (#505)

src/components/Table/components/TableSettings/index.tsx, src/components/Table/components/TableSettings/types.ts, src/components/Table/constants.ts, src/components/Table/index.tsx, src/components/Table/types.ts
=> feat: Remove remember settings check

src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/index.tsx
Fix Build PipelineRuns request params in Branch widget
Fixes #581 
=> fix: PipelineRuns request in branch

src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/index.tsx
=> fix: Latest build pipeline run progress

src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx, src/pages/stage-details/components/Applications/hooks/useColumns.tsx, src/pages/stage-details/components/ApplicationsWrapper/index.tsx
Fix applications deploy render: image stream tag select reset on data update
Fix columns resizing
Fixes #588 
=> fix: Applications deploy render (#588)

src/components/Table/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/Edit/components/Form/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/Edit/hooks/useDefaultValues.ts
=> feat: Add cdpipeline description edit

src/components/TooltipWithLinkList/index.tsx, src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/index.tsx, src/pages/stage-details/components/Applications/hooks/useColumns.tsx
=> feat: Add ingresses in stage app

src/components/CopyButton/index.tsx, src/components/Section/index.tsx, src/components/Section/types.ts, src/icons/iconify-icons-mapping.ts, src/pages/cdpipeline-details/view.tsx, src/pages/component-details/view.tsx, src/pages/configuration/pages/pipeline-details/view.tsx, src/pages/configuration/pages/task-details/view.tsx, src/pages/pipeline-details/view.tsx, src/pages/stage-details/view.tsx
=> feat: Add copy button

src/pages/component-list/components/ComponentList/components/ComponentMultiDeletion/index.tsx, src/widgets/ManageJiraServer/hooks/useResetIntegration.ts
Fix previous pull request (CDPipeline custom deletion message) lint stage
Fixes #596 
=> fix: CDpipeline message pr lint 

src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/components/ApplicationCard/index.tsx
Move ingress button in stage app block
Fixes #592 
=> feat: Move ingress button (#592)

Dockerfile, package-lock.json, package.json, src/components/LogViewer/index.tsx, src/components/Table/components/TableBody/index.tsx, src/components/Table/components/TableHead/components/TableRow/index.tsx, src/components/Table/components/TableSettings/index.tsx, src/components/Table/index.tsx, src/k8s/groups/Tekton/PipelineRun/utils/createRerunPipelineRunInstance/index.ts
Add xterm link addon which adds text processor to detect links
Fix table settings selection
Update table settings close callback
Update rerun pipeline run creation to remove "r-" identifier if present
Fixes #603 
=> feat: Add xterm link addon

src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx
Add copy button to branch name and vcs tag in pipeline list table
Fixes #598
=> fix: Add copy button to branch name and vcs tag (#598)

src/pages/pipeline-details/components/Details/index.tsx
=> fix: Pipeline page router history change

src/pages/stage-details/components/Applications/hooks/useConfigurationHandlers.ts
=> fix: Values override value

src/components/Table/components/TableHead/components/TableRow/index.tsx, src/components/Table/components/TableHead/components/TableRow/types.ts, src/components/Table/components/TableHead/index.tsx, src/components/Table/components/TableHead/types.ts, src/components/Table/components/TableSettings/index.tsx, src/components/Table/components/TableSettings/utils.ts, src/components/Table/index.tsx, src/components/Table/types.ts, src/pages/cdpipeline-list/components/CDPipelineList/hooks/useColumns.tsx, src/pages/component-list/components/ComponentList/hooks/useColumns.tsx, src/pages/configuration/pages/quicklinks/components/ComponentList/hooks/useColumns.tsx, src/pages/marketplace/components/MarketplaceList/components/TemplatesTable/hooks/useColumns.tsx, src/pages/stage-details/components/Applications/hooks/useColumns.tsx, src/widgets/PipelineList/hooks/useColumns.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx, src/widgets/TaskList/hooks/useColumns.tsx
Add table columns resize
Fixes #613 
=> feat: Add table columns resize

Dockerfile, src/components/PageLogicWrapper/index.tsx, src/components/Table/components/TablePagination/index.tsx, src/components/Table/constants.ts, src/index.tsx, src/pages/stage-details/components/Applications/components/ImageStreamTagsSelect/index.tsx, src/providers/Filter/components/Filter/index.tsx, src/widgets/AIChat/index.tsx, src/widgets/AIChat/utils.ts, src/widgets/ResourceQuotas/index.tsx
Update pagination rows per page options
Move AI Assistant to topbar
Fix ResourceQuotas widget console errors 
Fixes #615 
=> fix: Pagination and topbar items

src/widgets/dialogs/ManageCDPipeline/components/Create/components/FormActions/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/index.tsx
=> fix: CDPipeline create validation

src/pages/component-details/components/Overview/hooks/useInfoRows.tsx
=> feat: Unhide pipeline columns for gitops

src/pages/component-details/components/Overview/hooks/useInfoRows.tsx, src/pages/component-details/providers/DynamicData/provider.tsx, src/pages/component-list/components/ComponentList/index.tsx, src/pages/stage-details/hooks/useInfoColumns.tsx, src/widgets/Pipeline/index.tsx, src/widgets/dialogs/ManageCodebase/components/Create/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageCodebase/types.ts
=> fix: Component page crash 

Dockerfile
=> fix: Root page token expire state

Dockerfile, src/components/LogViewer/index.tsx
Add hidden logs output in html for testing purposes
Fixes #621 
=> feat: Add hidden logs output

src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/index.tsx
Fix pipeline list infinite load
Fixes #627 
=> fix: Pipeline list infinite load

src/widgets/dialogs/PodsTerminal/index.tsx
Fix terminal pod change crash
Fixes #629 
=> fix: Terminal pod change 

deploy-templates/templates/deployment.yaml
Fix Deployment manifest generation issue when `config.oidc.enabled` flag is set to `false`.
Fixes #631
=> fix: Fix Deployment manifest generation issue (#631)

src/components/TextWithTooltip/index.tsx, src/pages/cdpipeline-details/components/StageList/index.tsx
=> fix: Text with tooltip 

src/k8s/groups/default/Secret/labels.ts, src/k8s/groups/default/Secret/utils/createClusterSecretInstance/index.test.ts, src/k8s/groups/default/Secret/utils/createClusterSecretInstance/index.ts, src/widgets/AIChat/index.tsx, src/widgets/ManageClusterSecret/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageClusterSecret/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageClusterSecret/components/Create/components/Form/index.tsx, src/widgets/ManageClusterSecret/components/Create/components/FormActions/index.tsx, src/widgets/ManageClusterSecret/components/Create/index.tsx, src/widgets/ManageClusterSecret/components/Edit/components/Form/index.tsx, src/widgets/ManageClusterSecret/components/Edit/components/FormActions/index.tsx, src/widgets/ManageClusterSecret/components/Edit/hooks/useDefaultValues.ts, src/widgets/ManageClusterSecret/components/fields/CaData/index.tsx, src/widgets/ManageClusterSecret/components/fields/ClusterCertificate/index.tsx, src/widgets/ManageClusterSecret/components/fields/ClusterName/index.tsx, src/widgets/ManageClusterSecret/components/fields/ClusterToken/index.tsx, src/widgets/ManageClusterSecret/components/fields/ClusterType/index.tsx, src/widgets/ManageClusterSecret/components/fields/RoleARN/index.tsx, src/widgets/ManageClusterSecret/components/fields/SkipTLSVerify/index.tsx, src/widgets/ManageClusterSecret/components/fields/index.ts, src/widgets/ManageClusterSecret/constants.ts, src/widgets/ManageClusterSecret/names.ts, src/widgets/ManageClusterSecret/types.ts, src/widgets/dialogs/PodsTerminal/index.tsx
=> feat: Add irsa cluster create option

src/widgets/ManageClusterSecret/components/Edit/hooks/useDefaultValues.ts
=> fix: Cluster name value irsa

Dockerfile, src/pages/overview-list/route.tsx, src/routes/sidebar-list.ts
=> fix: Root page token expire

src/k8s/common/labels.ts, src/utils/actions/createResourceAction/index.test.ts, src/utils/actions/createResourceAction/index.ts
=> feat: Update edit protection

src/pages/cdpipeline-list/components/CDPipelineList/hooks/useFilter.tsx, src/pages/cdpipeline-list/components/CDPipelineList/index.tsx, src/pages/cdpipeline-list/components/CDPipelineList/types.ts, src/pages/cdpipeline-list/constants.ts, src/pages/cdpipeline-list/page.tsx, src/pages/cdpipeline-list/types.ts, src/pages/cdpipeline-list/view.tsx
=> feat: Add filter by app in dflow list 

src/configs/select-options/codebaseVersioningTypes.ts, src/constants/codebaseVersioningTypes.ts, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/pages/component-details/components/Overview/hooks/useInfoRows.tsx, src/widgets/ManageGitOps/hooks/useDefaultValues.ts, src/widgets/dialogs/CreateCodebaseFromTemplate/components/Form/hooks/useUpdateVersioningFields.ts, src/widgets/dialogs/CreateCodebaseFromTemplate/components/fields/CodebaseVersioning/index.tsx, src/widgets/dialogs/CreateCodebaseFromTemplate/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/hooks/useUpdateVersioningFields.ts, src/widgets/dialogs/ManageCodebase/components/Create/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageCodebase/components/fields/CodebaseVersioning/index.tsx, src/widgets/dialogs/ManageCodebaseBranch/components/Create/components/Form/index.tsx, src/widgets/dialogs/ManageCodebaseBranch/components/Create/hooks/useDefaultValues.ts
=> feat: Update edp versioning name (#650)

src/pages/stage-details/hooks/usePageTabs.tsx
=> feat: Disable monitoring button for non grafana providers

Dockerfile, src/components/Table/components/TableHead/components/TableRow/index.tsx
Fix selection "select all" button state
Fixes #(issue)
=> fix: Select all btn state 

Dockerfile
=> chore: Align base headlamp image version

Dockerfile, src/pages/cdpipeline-details/components/StageList/components/EnvironmentStage/index.tsx, src/widgets/dialogs/ManageCodebase/components/fields/CodebaseVersioning/index.tsx
=> feat: Update kubecfg preview 

Dockerfile, src/k8s/groups/default/ConfigMap/constants.ts, src/k8s/groups/default/ConfigMap/hooks/useEDPConfigMap.ts, src/k8s/groups/default/ConfigMap/index.ts, src/pages/component-details/providers/Data/provider.tsx, src/pages/configuration/pages/registry/providers/DynamicData/provider.tsx, src/pages/pipelines/pages/pipeline-run-details/providers/DynamicData/provider.tsx, src/widgets/dialogs/ManageStage/components/fields/Cluster/index.tsx, src/widgets/dialogs/ManageVCluster/providers/CurrentDialog/provider.tsx
Update EDP config query to take into account different possisble names of edp config ('edp-config', 'krci-config')
Fixes #669 
=> fix: Edp config query

src/providers/Form/components/FormCheckbox/index.tsx, src/widgets/ManageClusterSecret/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageClusterSecret/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageGitServer/__snapshots__/index.create.test.tsx.snap, src/widgets/ManageGitServer/__snapshots__/index.edit.test.tsx.snap, src/widgets/ManageRegistry/__snapshots__/index.edit.test.tsx.snap, src/widgets/dialogs/CreateCodebaseFromTemplate/components/Form/index.tsx, src/widgets/dialogs/CreateCodebaseFromTemplate/components/fields/Private/index.tsx, src/widgets/dialogs/CreateCodebaseFromTemplate/components/fields/index.ts, src/widgets/dialogs/CreateCodebaseFromTemplate/hooks/useDefaultValues.ts, src/widgets/dialogs/CreateCodebaseFromTemplate/names.ts, src/widgets/dialogs/ManageCodebase/__snapshots__/index.test.tsx.snap, src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/components/Info/index.tsx, src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/index.tsx, src/widgets/dialogs/ManageCodebase/components/Create/hooks/useDefaultValues.ts, src/widgets/dialogs/ManageCodebase/components/fields/Private/index.tsx, src/widgets/dialogs/ManageCodebase/components/fields/index.ts, src/widgets/dialogs/ManageCodebase/names.ts, src/widgets/dialogs/ManageCodebaseBranch/__snapshots__/index.test.tsx.snap, src/widgets/dialogs/ManageQuickLink/__snapshots__/index.test.tsx.snap
=> feat: Add codebase field private

src/k8s/groups/Tekton/Pipeline/labels.ts, src/pages/pipelines/components/index.tsx, src/pages/pipelines/pages/pipeline-details/components/Overview/index.tsx, src/pages/pipelines/pages/pipeline-details/view.tsx, src/pages/pipelines/pages/pipeline-list/view.tsx, src/widgets/PipelineActionsMenu/index.tsx, src/widgets/PipelineActionsMenu/types.ts, src/widgets/PipelineList/components/Actions/index.tsx, src/widgets/PipelineList/hooks/useColumns.tsx, src/widgets/PipelineList/index.tsx, src/widgets/PipelineList/types.ts, src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/components/Info/index.tsx
Add Private field for clone strategy
Remove type filter in pipelines page
Update pipelines pages docs links
Add pipelinerun template from triggertemplate for run pipeline logic
Fixes #678 
=> feat: Add run from triggertemplate

src/k8s/groups/Tekton/PipelineRun/utils/createPipelineRunInstanceFromPipeline/index.test.ts, src/k8s/groups/Tekton/PipelineRun/utils/createPipelineRunInstanceFromPipeline/index.ts, src/widgets/PipelineActionsMenu/index.tsx, src/widgets/dialogs/ManageCodebase/names.ts
=> fix: Codebase validation tab change 

src/k8s/groups/Tekton/PipelineRun/utils/createPipelineRunInstanceFromPipeline/index.ts, src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx, src/pages/pipelines/pages/pipeline-run-details/providers/DynamicData/provider.tsx, src/pages/pipelines/pages/pipeline-run-details/view.tsx, src/widgets/PipelineRunGraph/index.tsx
Fix case when PipelineRun is created from custom pipeline with errors, so when there are no tasks/taskruns user should see user-friendly message instead of wrong loading state
Fixes #678
=> fix: No tasks/taskruns loading state

src/k8s/groups/default/Secret/annotations.ts, src/pages/configuration/pages/clusters/view.tsx
=> feat: Add cluster secret status 

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md, package-lock.json, package.json
=> chore: Update current development version (#688)

Dockerfile
=> chore: Update image

src/widgets/LogViewer/index.tsx
=> fix: Sonar error

Dockerfile
=> chore: Update image version 

CHANGELOG.md, deploy-templates/Chart.yaml
=> chore: Update current development version (#699)

src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx, src/pages/pipelines/pages/pipeline-run-details/components/ReserveLogs/hooks/useTabs.tsx, src/pages/pipelines/pages/pipeline-run-details/hooks/useTabs.tsx, src/pages/pipelines/pages/pipeline-run-details/providers/DynamicData/provider.tsx, src/pages/pipelines/pages/pipeline-run-details/view.tsx
Fix PipelineRun page conditional rendering(error/reserve logs/pipelinerun) after previous ts errors fixes
=> fix: Pipelinerun page conditional rendering

src/constants/urls.ts, src/pages/cdpipeline-details/view.tsx, src/pages/component-details/components/Overview/index.tsx, src/pages/component-details/view.tsx, src/pages/configuration/pages/clusters/constants.ts, src/pages/configuration/pages/gitservers/constants.ts, src/pages/configuration/pages/quicklinks/constants.ts, src/pages/marketplace/view.tsx, src/pages/overview-list/view.tsx, src/pages/pipelines/pages/pipeline-list/constants.ts, src/pages/pipelines/pages/pipeline-run-list/constants.ts, src/pages/pipelines/pages/task-list/constants.ts, src/pages/stage-details/view.tsx, src/widgets/dialogs/CreateCodebaseFromTemplate/__snapshots__/index.test.tsx.snap, src/widgets/dialogs/CreateCodebaseFromTemplate/components/Preview/index.tsx
Add new docs links for widgets like SonarQube, Pipelines section.
Update old links with more accurate docs pages
Fixes #704 
=> feat: Add new docs links, update others

src/widgets/PipelineActionsMenu/index.tsx
=> fix: Pipelinerun create from pipeline

Dockerfile
=> fix: Kubecfg show on first try 

src/components/RefPortal/index.tsx, src/components/Table/components/TableBody/components/TableRow/index.tsx, src/components/Table/components/TableBody/components/TableRow/types.ts, src/components/Table/components/TableBody/index.tsx, src/components/Table/components/TableBody/types.ts, src/components/Table/components/TableHead/index.tsx, src/components/Table/components/TableHead/types.ts, src/components/Table/index.tsx, src/components/Table/types.ts, src/components/TileChart/styles.ts, src/pages/component-list/components/ComponentActions/index.tsx, src/pages/overview-list/components/AddNewWidget/index.tsx, src/pages/overview-list/components/AddNewWidget/styles.ts, src/pages/overview-list/components/UserWidgetsRenderer/index.tsx, src/pages/overview-list/page.tsx, src/pages/overview-list/providers/UserWidgets/index.tsx, src/pages/overview-list/view.tsx, src/widgets/AppVersion/hooks/useColumns.tsx, src/widgets/AppVersion/index.tsx, src/widgets/dialogs/AddNewWidget/components/DialogInner/Configuration/index.tsx, src/widgets/dialogs/AddNewWidget/components/DialogInner/Selection/index.tsx, src/widgets/dialogs/AddNewWidget/components/DialogInner/index.tsx, src/widgets/dialogs/AddNewWidget/constants.ts, src/widgets/dialogs/AddNewWidget/forms/AppVersionWidgetForm/index.tsx, src/widgets/dialogs/AddNewWidget/index.tsx, src/widgets/dialogs/AddNewWidget/providers/CurrentDialog/context.ts, src/widgets/dialogs/AddNewWidget/providers/CurrentDialog/hooks.ts, src/widgets/dialogs/AddNewWidget/providers/CurrentDialog/provider.tsx, src/widgets/dialogs/AddNewWidget/providers/CurrentDialog/types.ts, src/widgets/dialogs/AddNewWidget/types.ts
Add ability to add custom widgets to overview dashboard.
Currently, only Deployed Application Versions is available.
Fixes #709 
=> feat: Add ability to add custom widgets

Dockerfile, src/providers/Form/components/FormAutocomplete/index.tsx
=> fix: Autocomplete numtag spacing

src/widgets/ManageGitServer/providers/Data/context.ts, src/widgets/ManageGitServer/providers/Data/index.tsx
=> fix: Gitserver create cancel btn

src/providers/Filter/constants.ts
=> fix: Filter search function 

Dockerfile, package.json, src/widgets/PipelineActionsMenu/index.tsx
=> fix: Prod source maps

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md, package-lock.json, package.json
=> chore: Update current development version (#725)

src/components/CopyButton/index.tsx, src/components/Section/index.tsx, src/pages/stage-details/components/Applications/hooks/useColumns.tsx, src/pages/stage-details/components/Applications/index.tsx, src/providers/Form/components/FormAutocomplete/index.tsx, src/providers/Form/components/FormAutocompleteSingle/index.tsx, src/providers/Form/components/FormControlLabelWithTooltip/index.tsx, src/providers/Form/components/FormTextField/index.tsx, src/providers/Form/components/FormTextFieldEditable/index.tsx, src/providers/Form/components/FormTextFieldEncoded/index.tsx, src/providers/Form/components/FormTextFieldPassword/index.tsx, src/widgets/dialogs/ManageCDPipeline/components/fields/Applications/index.tsx, src/widgets/dialogs/ManageStage/components/fields/QualityGates/index.tsx
Add copy deployed environment applications versions 
Fixes #730 
=> feat: Add copy deployed versions btn

src/pages/pipelines/pages/pipeline-details/page.tsx
=> fix: Pipeline page filter context 

src/providers/Filter/constants.ts
=> fix: Filter by label function in search (#743)

src/components/DataGrid/index.tsx, src/components/EmptyList/index.tsx, src/components/Section/index.tsx, src/pages/cdpipeline-details/components/StageList/index.tsx, src/pages/cdpipeline-list/components/CDPipelineList/index.tsx, src/pages/component-details/components/CodebaseBranchesList/components/CodebaseBranch/components/Summary/index.tsx, src/pages/stage-details/hooks/useInfoColumns.tsx, src/providers/Filter/components/Filter/index.tsx, src/widgets/PipelineList/index.tsx, src/widgets/PipelineRunList/hooks/useColumns.tsx, src/widgets/PipelineRunList/hooks/useFilter.tsx, src/widgets/PipelineRunList/index.tsx, src/widgets/TaskList/index.tsx
In pipelinerun list filter reset doesn't work correctly
Fix alignment of filter's controls and reset button everywhere within the app
Fix empty result for marketplace list datagrid filter 
Fix UI flickering when setting/resetting filter values
Fixes #748
=> fix: Filter issues 

src/utils/formFieldValidation.ts
=> fix: Git url path regexp

src/k8s/groups/EDP/CodebaseBranch/utils/createCodebaseBranchInstance/index.test.ts, src/k8s/groups/EDP/CodebaseBranch/utils/createCodebaseBranchInstance/index.ts
Fix branch name truncation when creating
Fixes #753 
=> fix: Branch truncation

src/constants/pipelineTypes.ts, src/pages/pipelines/pages/pipeline-list/page.tsx, src/widgets/PipelineList/constants.ts, src/widgets/PipelineList/index.tsx, src/widgets/PipelineList/types.ts, src/widgets/PipelineRunList/hooks/useFilter.tsx, src/widgets/PipelineRunList/index.tsx
=> feat: Add pipelinetype select for pipeline list 

.github/workflows/codeql.yaml, .github/workflows/pr.yaml, .github/workflows/release.yaml
=> chore: Update codeql and codecov scan gh actions (#764)

src/components/TooltipWithLinkList/index.tsx, src/k8s/groups/EDP/QuickLink/constants.ts, src/pages/stage-details/components/Applications/components/ValuesOverrideSwitch/index.tsx, src/pages/stage-details/components/Applications/hooks/useColumns.tsx, src/pages/stage-details/components/Applications/index.tsx, src/widgets/dialogs/ManageCodebaseBranch/providers/CurrentDialog/context.ts
Optimize Ingress feature in KubeRocketCI UI Portal for large object lists and host-only filtering
Add confirmation dialog/notification when switching the 'values override' flag
Copy Environment Deployed Version button copies incorrect namespace
Fixes #766
=> fix: Improve deployment page features 

Dockerfile
=> chore: Update snapshot (#769)

src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx, src/pages/pipelines/pages/pipeline-run-details/providers/DynamicData/provider.tsx, src/pages/pipelines/pages/pipeline-run-details/view.tsx
Fix bug situation where api url from krci config is empty and pipelinerun page falls into infinite loading trying to load external logs
Fixes #784
=> fix: Pipelinerun page with no available api url (#784)

src/k8s/groups/Tekton/PipelineRun/hooks/usePipelineRunData.ts, src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx
=> fix: Pipelinerun page white if no approval tasks 

src/k8s/groups/Tekton/PipelineRun/hooks/usePipelineRunData.ts, src/pages/pipelines/pages/pipeline-run-details/components/Details/index.tsx
=> fix: Pipelinerun page white if no approval tasks

src/pages/pipelines/pages/pipeline-run-history-list/logs.query.ts
Fix pipelineruns history logs all query
Fixes #(issue)
=> fix: Query for pipelineruns history

src/pages/configuration/pages/registry/providers/DynamicData/provider.tsx, src/providers/MultiForm/context.ts, src/providers/MultiForm/provider.tsx, src/providers/MultiForm/types.ts, src/widgets/ManageRegistry/components/Actions/index.tsx, src/widgets/ManageRegistry/hooks/useSharedForm.ts, src/widgets/dialogs/ManageCodebaseBranch/components/fields/FromCommit/index.tsx
Fix issues for release 0.23
Fixes #791 
=> fix: Issues for release 0.23 

src/services/api/index.ts, src/widgets/dialogs/ManageCodebase/components/Create/components/Inner/components/Form/components/Info/index.tsx, src/widgets/dialogs/ManageCodebase/components/fields/Owner/index.tsx, src/widgets/dialogs/ManageCodebase/components/fields/Repository/index.tsx
Fix case when api-gateway-url is undefined and users cannot onboard codebases/branches
Add cache-control no-cache header for requests to api-gateway
Fixes #791 
=> fix: Cover no apibaseurl case for codebases onboarding 

src/widgets/dialogs/ManageCodebaseBranch/components/fields/FromCommit/index.tsx
Make fromcommit field to be free solo
Fixes #791 
=> fix: Fromcommit field free solo mode (#791)

CHANGELOG.md, deploy-templates/Chart.yaml, deploy-templates/README.md, package-lock.json, package.json
=> chore: Update current development version (#798)

src/widgets/dialogs/ManageCodebase/components/fields/Owner/index.tsx, src/widgets/dialogs/ManageCodebase/components/fields/Repository/index.tsx, src/widgets/dialogs/ManageCodebaseBranch/__snapshots__/index.test.tsx.snap, src/widgets/dialogs/ManageCodebaseBranch/components/fields/BranchName/index.tsx, src/widgets/dialogs/ManageCodebaseBranch/components/fields/FromCommit/index.tsx
Fix branch dialog discovery error
Fixes #791 
=> fix: Branch dialog discovery errors

Dockerfile
=> fix: Auth test (#815)

Dockerfile
=> fix: Auth test 3 (#815)
